version: '3.8'

services:
    frontend-ppd:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - VITE_API_URL=${VITE_API_URL}
                - VITE_APP_ENV=${VITE_APP_ENV}
        container_name: patens-frontend-${VITE_APP_ENV}
        restart: unless-stopped
        ports:
            - '5173:80'
        # networks:
        #     - patens-network
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        environment:
            - NODE_ENV=production
            - VITE_API_URL=${VITE_API_URL}
            - VITE_APP_ENV=${VITE_APP_ENV}
# networks:
#     patens-network:
#         driver: bridge
