name: Deploy Vite Frontend to Scaleway Bucket

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build Vite app
              run: npm run build

            - name: Sync to Scaleway Bucket
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
                  AWS_REGION: ${{ secrets.S3_REGION }}
                  SOURCE_DIR: 'dist'
