name: Deploy Vite Frontend to Scaleway via rclone

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build Vite app
              run: npm run build

            - name: Install rclone
              run: |
                  curl https://rclone.org/install.sh | sudo bash

            - name: Configure rclone
              run: |
                  mkdir -p ~/.config/rclone
                  echo "[scaleway]" > ~/.config/rclone/rclone.conf
                  echo "type = s3" >> ~/.config/rclone/rclone.conf
                  echo "provider = Minio" >> ~/.config/rclone/rclone.conf
                  echo "access_key_id = ${{ secrets.S3_ACCESS_KEY }}" >> ~/.config/rclone/rclone.conf
                  echo "secret_access_key = ${{ secrets.S3_SECRET_KEY }}" >> ~/.config/rclone/rclone.conf
                  echo "region = fr-par" >> ~/.config/rclone/rclone.conf
                  echo "endpoint = https://s3.fr-par.scw.cloud" >> ~/.config/rclone/rclone.conf
                  echo "location_constraint = fr-par" >> ~/.config/rclone/rclone.conf
                  echo "acl = public-read" >> ~/.config/rclone/rclone.conf

            - name: Sync to Scaleway bucket
              run: |
                  rclone sync dist scaleway:grunda-frontend-test \
                    --s3-acl public-read \
                    --ignore-times \
                    --progress
