name: Deploy Vite Frontend to Scaleway Bucket

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build Vite app
              run: npm run build

            - name: Install AWS CLI
              run: |
                  sudo apt-get update
                  sudo apt-get install -y awscli

            - name: Sync to Scaleway Object Storage (S3-compatible)
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
              run: |
                  aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }}/ \
                    --endpoint-url https://s3.fr-par.scw.cloud \
                    --acl public-read \
                    --delete
